create table notes (
  note_id INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL DEFAULT 1,
  title VARCHAR(100),
  content TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);